num_joints: 17
max_people: 4
feat_dim: 3
radius: 0.1
nsamples: 32
spatial_stride: 32
temporal_kernel_size: 3  
temporal_stride: 1 
emb_relu: false 
dim: 1024  
depth: 10  
heads: 8  
dim_head: 256 
mlp_dim: 2048  
dropout1: 0.0  
dropout2: 0.0 