experiment:
  description: HRRadarPose baseline using high radar bin
  output_path: /home/pai/Huawei/experiments

data:
    # NAS 地址
    root_path: /mnt/huawei
    # SSD Bin 地址
    radar_bin_root: /mnt/ssd/Huawei
    # 时钟基准
    base_source: radar_high_bin
    ratio: 0.7
    T: 1
    split_method: group
    max_points: 300
    max_people: 4
    num_workers: 8
    preload_cache: true
    enable_action: false
    enable_rotation_train: false
    enable_rotation_val: false
    sensor_config:
        lidar: false
        radar_low_bin: false
        radar_high_bin: true
        radar_low_pc: false
        radar_high_pc: false
        gt: true
        realsense: false
    xyz_limits:
        - [0.0, 6.0]
        - [-3.0, 3.0]
        - [-2.0, 2.0]
    # RPM2
    map_size: [256, 256]
    # HRRadarPose
    cube_size: [96, 96, 32]
    # BIN 预处理：在频移 FFT/角度谱计算前扣除 chirp 维复数均值
    remove_static: false
model:
    name: HRRadarPose

radar:
    angle_method: bartlett

task:
    stage: train
    input: radar_high_bin
    output: gt_for_high
    device: 1
    seed: 42
    batch_size: 4
    # 数值精度: FP32 / FP16 / BF16
    precision: BF16
    # 匈牙利匹配
    matching_for_hungarian:
        bbox_l1_weight: 5.0
        bbox_iou_weight: 2.0
    # 坐标归一化，仅适配于点云
    center_on_hip: false
    train:
        epoch: 500
        init_lr: 0.001
        warmup_epoch: 10
        resume:
          enabled: false
          checkpoint_path: /home/pai/Huawei/experiments/HRRadarPose/20260901_150207/checkpoint/last.pth
        metrics:
            # Pose loss
            MPJPE: 0
            PAMPJPE: 0
            Bone_Length: 0
            # Detection loss
            bbox_iou: 0
            bbox_l1: 0
            objectness: 0
            # RPM2 loss
            rpm2_center_heatmap: 0
            rpm2_center_offset: 0
            rpm2_box_size: 0
            rpm2_pose: 0
            # HRRadarPose loss
            hrradarpose_body_center: 1.0
            hrradarpose_keypoint_offset: 1.0
        best_metric: loss
        shuffle: true
    val:
        checkpoint_path: none
        shuffle: false
        score_thresh: 0.1
        iou_thresh: 0.7
        metrics:
            # Pose loss
            MPJPE: 0
            PAMPJPE: 0
            Bone_Length: 0
            # Detection loss
            bbox_iou : 0
            bbox_l1: 0
            objectness: 0
            # RPM2 loss
            rpm2_center_heatmap: 0
            rpm2_center_offset: 0
            rpm2_box_size: 0
            rpm2_pose: 0
            # HRRadarPose loss
            hrradarpose_body_center: 1.0
            hrradarpose_keypoint_offset: 1.0
