experiment:
  description: P4Transformer baseline using high radar point cloud
  output_path: /home/pai/Huawei/experiments

data:
    root_path: /mnt/huawei
    base_source: radar_high_pc
    ratio: 0.7
    T: 8
    split_method: person
    max_points: 200
    max_people: 4
    num_workers: 8
    preload_cache: true
    sensor_config:
        lidar: false
        radar_low_bin: false
        radar_high_bin: false
        radar_low_pc: false
        radar_high_pc: true
        gt: true
        realsense: false
    point_cloud_range:
        - 0.0
        - -3.0
        - -2.0
        - 6
        - 3.0
        - 2.0
model:
    name: P4Transformer

task:
    stage: train
    input: radar_high_pc
    output: gt_for_high
    device: 1
    seed: 42
    batch_size: 8
    matching_for_hungarian:
        bbox_l1_weight: 5.0
        bbox_iou_weight: 2.0
    train:
        epoch: 300
        init_lr: 0.001
        warmup_epoch: 10
        resume:
          enabled: false
          checkpoint_path: none
        metrics: 
            MPJPE: 1
            PAMPJPE: 0
            Bone_Length: 0
            bbox_iou: 0
            bbox_l1: 0
            objectness: 0
        best_metric: loss
        shuffle: true
    val:
        checkpoint_path: /home/pai/Huawei/experiments/P4Transformer/20260728_203033/checkpoint/best.pth
        shuffle: false
        score_thresh: 0.1
        iou_thresh: 0.7
        metrics: 
            MPJPE: 1
            PAMPJPE: 0
            Bone_Length: 0
            bbox_iou : 0
            bbox_l1: 0
            objectness: 0
