inchannels: 3
stage2_num_modules: 1
stage2_num_branches: 2
stage2_block: BASIC
stage2_num_blocks:
  - 4
  - 4
stage2_num_channels:
  - 18
  - 36
stage2_fuse_method: SUM

stage3_num_modules: 1
stage3_num_branches: 3
stage3_block: BASIC
stage3_num_blocks:
  - 4
  - 4
  - 4
stage3_num_channels:
  - 18
  - 36
  - 72
stage3_fuse_method: SUM

stage4_num_modules: 1
stage4_num_branches: 4
stage4_block: BASIC
stage4_num_blocks:
  - 4
  - 4
  - 4
  - 4
stage4_num_channels:
  - 18
  - 36
  - 72
  - 144
stage4_fuse_method: SUM
